# Generated by Django 3.1.2 on 2021-01-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizID', models.IntegerField(default=0)),
                ('question', models.CharField(max_length=200)),
                ('option_1', models.CharField(max_length=100)),
                ('option_2', models.CharField(max_length=100)),
                ('option_3', models.CharField(max_length=100)),
                ('option_4', models.CharField(max_length=100)),
                ('corret_choice', models.IntegerField(choices=[('1', '1'), ('2', 2), ('3', '3'), ('4', '4')], default=1)),
            ],
        ),
    ]
