# Generated by Django 3.1.2 on 2021-01-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_answer',
            name='corret_choice',
        ),
        migrations.AddField(
            model_name='question_answer',
            name='correct_choice',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1),
        ),
    ]
