# Generated by Django 3.1.2 on 2021-01-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210125_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_answer',
            name='option_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question_answer',
            name='option_2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question_answer',
            name='option_3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question_answer',
            name='option_4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question_answer',
            name='question',
            field=models.TextField(),
        ),
    ]
