# Generated by Django 3.1.2 on 2021-01-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_auto_20210114_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='year',
            field=models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Pre-Final'), ('4', 'Final'), ('5', 'Alumni')], max_length=6),
        ),
    ]
