# Generated by Django 3.1.2 on 2021-01-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_eventregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregister',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=8),
        ),
        migrations.AlterField(
            model_name='eventregister',
            name='year',
            field=models.CharField(max_length=15),
        ),
    ]
