# Generated by Django 3.1.2 on 2021-01-14 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0005_auto_20210114_2322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventRegister',
            new_name='EventRegistration',
        ),
    ]
