# Generated by Django 3.1.2 on 2021-01-14 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0006_auto_20210115_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='slug',
        ),
    ]
