# Generated by Django 3.1.2 on 2021-01-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0007_remove_eventregistration_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='slug',
            field=models.SlugField(default='random', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
